# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4275690d5eea35362a79d27ebc6cdf5060aa4e3c9a55906c8443f76c59092b9af92ebca8c6ca421d28cb9d5232121fdc8beb9bbc2b9998613db907937c8abd7f

test:
  secret_key_base: 0a50600c28e6fd4673164b6010adef8fa3340ebe6cbda35489b3c91beb90aa696d0be38d10754541c03f342cdf83f0555dd59f68b6eabeb2d55e6012d797508b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
